package ocpi

import (
	"context"
	"net/http"
)

// This file implements the Charging Profiles module (mod_charging_profiles),
// which the Hub implements server-side. Field shapes mirror
// lib/ocpi/chargingProfiles.ts and lib/ocpi/schemas/chargingProfile.ts on
// the Hub.
//
// Like Commands, not symmetric CRUD: the client exposes one typed method
// per action (GetActiveChargingProfile, SetChargingProfile,
// DeleteChargingProfile) requested against an existing session, plus
// GetChargingProfile, whose GET route lives at
// /chargingprofiles/callback/{id} — not /chargingprofiles/{session_id}.
//
// ResponseURL is NOT generated by this SDK: unlike the Hub (which builds
// its own internal callback URL), a caller of this SDK is a real external
// eMSP and must pass its own public response_url; the SDK only forwards it
// verbatim in the body.
//
// POST /chargingprofiles/callback/{id} (called by the external CPO, not by
// an SDK client) is server-to-server infrastructure and is intentionally
// not exposed as a public method here.

// ChargingProfilePeriod is one period of a ChargingProfile's schedule.
type ChargingProfilePeriod struct {
	StartPeriod int     `json:"start_period"`
	Limit       float64 `json:"limit"`
}

// ChargingProfile describes a smart-charging power limit schedule
// (mod_charging_profiles).
type ChargingProfile struct {
	StartDateTime         string                  `json:"start_date_time,omitempty"`
	Duration              int                     `json:"duration,omitempty"`
	ChargingRateUnit      string                  `json:"charging_rate_unit"`
	MinChargingRate       float64                 `json:"min_charging_rate,omitempty"`
	ChargingProfilePeriod []ChargingProfilePeriod `json:"charging_profile_period"`
}

// getActiveChargingProfileRequest is the payload for
// POST /chargingprofiles/{cc}/{pid}/{sid}/GET_ACTIVE_CHARGING_PROFILE.
type getActiveChargingProfileRequest struct {
	ResponseURL string `json:"response_url"`
}

// SetChargingProfileRequest is the payload for
// POST /chargingprofiles/{cc}/{pid}/{sid}/PUT_CHARGING_PROFILE.
type SetChargingProfileRequest struct {
	ResponseURL     string          `json:"response_url"`
	ChargingProfile ChargingProfile `json:"charging_profile"`
}

// deleteChargingProfileRequest is the payload for
// POST /chargingprofiles/{cc}/{pid}/{sid}/DELETE_CHARGING_PROFILE.
type deleteChargingProfileRequest struct {
	ResponseURL string `json:"response_url"`
}

// ChargingProfileAckResult is the result field of a ChargingProfileAck.
type ChargingProfileAckResult string

const (
	ChargingProfileAckAccepted       ChargingProfileAckResult = "ACCEPTED"
	ChargingProfileAckRejected       ChargingProfileAckResult = "REJECTED"
	ChargingProfileAckUnknownSession ChargingProfileAckResult = "UNKNOWN_SESSION"
)

// ChargingProfileAck is the ACK returned directly as `data` of
// POST /chargingprofiles/{cc}/{pid}/{sid}/{action} — the immediate response
// from the target CPO, forwarded by the Hub as-is.
type ChargingProfileAck struct {
	Result  ChargingProfileAckResult `json:"result"`
	Timeout int                      `json:"timeout"`
}

// ChargingProfileFinalResult is the asynchronous, final outcome of a
// charging profile request, reported by the target CPO via
// POST /chargingprofiles/callback/{id} (or forced to FAILED by
// GetChargingProfile after 30s with no response).
type ChargingProfileFinalResult string

const (
	ChargingProfileFinalAccepted       ChargingProfileFinalResult = "ACCEPTED"
	ChargingProfileFinalRejected       ChargingProfileFinalResult = "REJECTED"
	ChargingProfileFinalFailed         ChargingProfileFinalResult = "FAILED"
	ChargingProfileFinalUnknownSession ChargingProfileFinalResult = "UNKNOWN_SESSION"
)

// ChargingProfileRequestRecord is the response shape of
// GET /chargingprofiles/callback/{id}.
type ChargingProfileRequestRecord struct {
	ID                    string                     `json:"id"`
	SessionID             string                     `json:"session_id"`
	Action                string                     `json:"action"`
	AckResult             ChargingProfileAckResult   `json:"ack_result,omitempty"`
	FinalResult           ChargingProfileFinalResult `json:"final_result,omitempty"`
	ChargingProfile       *ChargingProfile           `json:"charging_profile,omitempty"`
	FinalResultReceivedAt string                     `json:"final_result_received_at,omitempty"`
	LastUpdated           string                     `json:"last_updated"`
}

// ChargingProfileAckResponse is the full envelope returned by
// POST /chargingprofiles/{cc}/{pid}/{sid}/{action}.
type ChargingProfileAckResponse = Envelope[ChargingProfileAck]

// ChargingProfileRequestResponse is the full envelope returned by
// GET /chargingprofiles/callback/{id}.
type ChargingProfileRequestResponse = Envelope[ChargingProfileRequestRecord]

// GetActiveChargingProfile requests the active charging profile for
// sessionID from the CPO that owns it, via
// POST /chargingprofiles/{countryCode}/{partyID}/{sessionID}/GET_ACTIVE_CHARGING_PROFILE.
// Requires an EMSP role.
func (c *Client) GetActiveChargingProfile(ctx context.Context, tokenB, countryCode, partyID, sessionID, responseURL string) (*ChargingProfileAckResponse, error) {
	url := c.baseURL + "/chargingprofiles/" + countryCode + "/" + partyID + "/" + sessionID + "/GET_ACTIVE_CHARGING_PROFILE"
	return doRequest[ChargingProfileAck](ctx, c, http.MethodPost, url, tokenB, getActiveChargingProfileRequest{ResponseURL: responseURL})
}

// SetChargingProfile pushes a charging profile for sessionID to the CPO
// that owns it, via
// POST /chargingprofiles/{countryCode}/{partyID}/{sessionID}/PUT_CHARGING_PROFILE.
// Requires an EMSP role.
func (c *Client) SetChargingProfile(ctx context.Context, tokenB, countryCode, partyID, sessionID, responseURL string, profile ChargingProfile) (*ChargingProfileAckResponse, error) {
	url := c.baseURL + "/chargingprofiles/" + countryCode + "/" + partyID + "/" + sessionID + "/PUT_CHARGING_PROFILE"
	return doRequest[ChargingProfileAck](ctx, c, http.MethodPost, url, tokenB, SetChargingProfileRequest{ResponseURL: responseURL, ChargingProfile: profile})
}

// DeleteChargingProfile clears the charging profile for sessionID on the
// CPO that owns it, via
// POST /chargingprofiles/{countryCode}/{partyID}/{sessionID}/DELETE_CHARGING_PROFILE.
// Requires an EMSP role.
func (c *Client) DeleteChargingProfile(ctx context.Context, tokenB, countryCode, partyID, sessionID, responseURL string) (*ChargingProfileAckResponse, error) {
	url := c.baseURL + "/chargingprofiles/" + countryCode + "/" + partyID + "/" + sessionID + "/DELETE_CHARGING_PROFILE"
	return doRequest[ChargingProfileAck](ctx, c, http.MethodPost, url, tokenB, deleteChargingProfileRequest{ResponseURL: responseURL})
}

// GetChargingProfile calls GET /chargingprofiles/callback/{id} to fetch the
// current state of a previously-requested charging profile action. Any
// CONNECTED connection may call this. If more than 30s have elapsed
// without a callback, the Hub marks the request FAILED automatically
// before returning.
func (c *Client) GetChargingProfile(ctx context.Context, tokenB, chargingProfileID string) (*ChargingProfileRequestResponse, error) {
	url := c.baseURL + "/chargingprofiles/callback/" + chargingProfileID
	return doRequest[ChargingProfileRequestRecord](ctx, c, http.MethodGet, url, tokenB, nil)
}
