package ocpi

import (
	"context"
	"net/http"
)

// This file implements the Commands module (mod_commands), which the Hub
// implements server-side. Field shapes mirror lib/ocpi/commands.ts and
// lib/ocpi/schemas/command.ts on the Hub.
//
// The most asymmetric of the 5 modules: not CRUD. The client exposes one
// typed method per command_type (StartSession, ReserveNow, StopSession,
// UnlockConnector, CancelReservation) plus GetCommand, whose GET route
// lives at /commands/callback/{command_id} — not /commands/{command_type},
// since Next.js doesn't allow two differently-named dynamic segments
// ([command_type] and [command_id]) at the same route level.
//
// ResponseURL is NOT generated by this SDK: unlike the Hub (which builds
// its own internal callback URL), a caller of this SDK is a real external
// eMSP and must pass its own public response_url; the SDK only forwards it
// verbatim in the body.
//
// POST /commands/callback/{command_id} (called by the external CPO, not by
// an SDK client) is server-to-server infrastructure and is intentionally
// not exposed as a public method here.

// CommandTokenRef is the subset of CdrToken used in command payloads
// (no country_code/party_id).
type CommandTokenRef struct {
	UID        string    `json:"uid"`
	Type       TokenType `json:"type"`
	ContractID string    `json:"contract_id"`
}

// StartSessionCommand is the payload for POST /commands/START_SESSION.
type StartSessionCommand struct {
	ResponseURL string          `json:"response_url"`
	CountryCode string          `json:"country_code"`
	PartyID     string          `json:"party_id"`
	Token       CommandTokenRef `json:"token"`
	LocationID  string          `json:"location_id"`
	EvseUID     string          `json:"evse_uid,omitempty"`
}

// ReserveNowCommand is the payload for POST /commands/RESERVE_NOW.
type ReserveNowCommand struct {
	ResponseURL   string          `json:"response_url"`
	CountryCode   string          `json:"country_code"`
	PartyID       string          `json:"party_id"`
	Token         CommandTokenRef `json:"token"`
	ExpiryDate    string          `json:"expiry_date"`
	ReservationID string          `json:"reservation_id"`
	LocationID    string          `json:"location_id"`
	EvseUID       string          `json:"evse_uid,omitempty"`
}

// StopSessionCommand is the payload for POST /commands/STOP_SESSION.
type StopSessionCommand struct {
	ResponseURL string `json:"response_url"`
	CountryCode string `json:"country_code"`
	PartyID     string `json:"party_id"`
	SessionID   string `json:"session_id"`
}

// UnlockConnectorCommand is the payload for POST /commands/UNLOCK_CONNECTOR.
type UnlockConnectorCommand struct {
	ResponseURL string `json:"response_url"`
	CountryCode string `json:"country_code"`
	PartyID     string `json:"party_id"`
	SessionID   string `json:"session_id"`
}

// CancelReservationCommand is the payload for
// POST /commands/CANCEL_RESERVATION.
type CancelReservationCommand struct {
	ResponseURL string `json:"response_url"`
	CountryCode string `json:"country_code"`
	PartyID     string `json:"party_id"`
	SessionID   string `json:"session_id"`
}

// CommandAckResult is the result field of a CommandAck.
type CommandAckResult string

const (
	CommandAckAccepted       CommandAckResult = "ACCEPTED"
	CommandAckRejected       CommandAckResult = "REJECTED"
	CommandAckNotSupported   CommandAckResult = "NOT_SUPPORTED"
	CommandAckUnknownSession CommandAckResult = "UNKNOWN_SESSION"
)

// CommandAck is the ACK returned directly as `data` of
// POST /commands/{command_type} — the immediate response from the target
// CPO, forwarded by the Hub as-is (not wrapped in another object).
type CommandAck struct {
	Result  CommandAckResult `json:"result"`
	Timeout int              `json:"timeout"`
	Message map[string]any   `json:"message,omitempty"`
}

// CommandFinalResult is the asynchronous, final outcome of a Command,
// reported by the target CPO via POST /commands/callback/{command_id}
// (or forced to TIMEOUT by GetCommand after 30s with no response).
type CommandFinalResult string

const (
	CommandFinalAccepted           CommandFinalResult = "ACCEPTED"
	CommandFinalRejected           CommandFinalResult = "REJECTED"
	CommandFinalFailed             CommandFinalResult = "FAILED"
	CommandFinalTimeout            CommandFinalResult = "TIMEOUT"
	CommandFinalUnknownReservation CommandFinalResult = "UNKNOWN_RESERVATION"
)

// Command is the response shape of GET /commands/callback/{command_id}.
type Command struct {
	ID                    string             `json:"id"`
	Type                  string             `json:"type"`
	Payload               any                `json:"payload"`
	AckResult             CommandAckResult   `json:"ack_result,omitempty"`
	AckMessage            map[string]any     `json:"ack_message,omitempty"`
	FinalResult           CommandFinalResult `json:"final_result,omitempty"`
	FinalResultReceivedAt string             `json:"final_result_received_at,omitempty"`
	LastUpdated           string             `json:"last_updated"`
}

// CommandAckResponse is the full envelope returned by
// POST /commands/{command_type}.
type CommandAckResponse = Envelope[CommandAck]

// CommandResponse is the full envelope returned by
// GET /commands/callback/{command_id}.
type CommandResponse = Envelope[Command]

// StartSession sends a remote START_SESSION command to the CPO that owns
// cmd.LocationID, via POST /commands/START_SESSION. Requires an EMSP role.
func (c *Client) StartSession(ctx context.Context, tokenB string, cmd StartSessionCommand) (*CommandAckResponse, error) {
	url := c.baseURL + "/commands/START_SESSION"
	return doRequest[CommandAck](ctx, c, http.MethodPost, url, tokenB, cmd)
}

// ReserveNow sends a remote RESERVE_NOW command to the CPO that owns
// cmd.LocationID, via POST /commands/RESERVE_NOW. Requires an EMSP role.
func (c *Client) ReserveNow(ctx context.Context, tokenB string, cmd ReserveNowCommand) (*CommandAckResponse, error) {
	url := c.baseURL + "/commands/RESERVE_NOW"
	return doRequest[CommandAck](ctx, c, http.MethodPost, url, tokenB, cmd)
}

// StopSession sends a remote STOP_SESSION command to the CPO that owns
// cmd.SessionID, via POST /commands/STOP_SESSION. Requires an EMSP role.
func (c *Client) StopSession(ctx context.Context, tokenB string, cmd StopSessionCommand) (*CommandAckResponse, error) {
	url := c.baseURL + "/commands/STOP_SESSION"
	return doRequest[CommandAck](ctx, c, http.MethodPost, url, tokenB, cmd)
}

// UnlockConnector sends a remote UNLOCK_CONNECTOR command to the CPO that
// owns cmd.SessionID, via POST /commands/UNLOCK_CONNECTOR. Requires an
// EMSP role.
func (c *Client) UnlockConnector(ctx context.Context, tokenB string, cmd UnlockConnectorCommand) (*CommandAckResponse, error) {
	url := c.baseURL + "/commands/UNLOCK_CONNECTOR"
	return doRequest[CommandAck](ctx, c, http.MethodPost, url, tokenB, cmd)
}

// CancelReservation sends a remote CANCEL_RESERVATION command to the CPO
// that owns cmd.SessionID, via POST /commands/CANCEL_RESERVATION. Requires
// an EMSP role.
func (c *Client) CancelReservation(ctx context.Context, tokenB string, cmd CancelReservationCommand) (*CommandAckResponse, error) {
	url := c.baseURL + "/commands/CANCEL_RESERVATION"
	return doRequest[CommandAck](ctx, c, http.MethodPost, url, tokenB, cmd)
}

// GetCommand calls GET /commands/callback/{command_id} to fetch the current
// state of a previously-sent Command. Any CONNECTED connection may call
// this. If more than 30s have elapsed without a callback, the Hub marks
// the command TIMEOUT automatically before returning.
func (c *Client) GetCommand(ctx context.Context, tokenB, commandID string) (*CommandResponse, error) {
	url := c.baseURL + "/commands/callback/" + commandID
	return doRequest[Command](ctx, c, http.MethodGet, url, tokenB, nil)
}
